
        package com.isuwang.soa.hello.service;

        import com.isuwang.dapeng.core.Processor;
        import com.isuwang.dapeng.core.Service;
        import com.isuwang.dapeng.core.SoaGlobalTransactional;

        import java.util.concurrent.Future;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(version = "1.0.0")
        @Processor(className = "com.isuwang.soa.hello.HelloServiceCodec\$Processor")
        public interface HelloService {
        
            /**
            * 
            **/
            
            
               com.isuwang.soa.hello.domain.Hello sayHello( String content) throws com.isuwang.dapeng.core.SoaException;
              
          
        }
        