package com.isuwang.soa.hello.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class Hello{
        
            /**
            *
            **/
            public String content ;
            public String getContent(){ return this.content; }
            public void setContent(String content){ this.content = content; }

            public String content(){ return this.content; }
            public Hello content(String content){ this.content = content; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("content").append("\":\"").append(this.content).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      