package com.isuwang.soa.scala.hello

        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.dapeng.remoting.BaseCommonServiceClient
        import com.isuwang.soa.scala.hello.HelloServiceCodec._
        import scala.concurrent.{Future, Promise}
        import java.util.function.BiConsumer

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        object HelloServiceAsyncClient extends BaseCommonServiceClient("com.isuwang.soa.hello.service.HelloService", "1.0.0"){

        override def isSoaTransactionalProcess: Boolean = {

          var isSoaTransactionalProcess = false
          
          isSoaTransactionalProcess
        }

        
            /**
            * 
            **/
            def sayHello(content:String , timeout: Long) : scala.concurrent.Future[com.isuwang.soa.scala.hello.domain.Hello] = {

            initContext("sayHello");

            try {
              val _responseFuture = sendBaseAsync(sayHello_args(content), new SayHello_argsSerializer(), new SayHello_resultSerializer(), timeout).asInstanceOf[java.util.concurrent.CompletableFuture[sayHello_result]]

              val promise = Promise[com.isuwang.soa.scala.hello.domain.Hello]()

              _responseFuture.whenComplete(new BiConsumer[sayHello_result, Throwable]{

              override def accept(r: sayHello_result, e: Throwable): Unit = {
                if(e != null)
                  promise.failure(e)
                else
                  promise.success(r.success)
                }
              })
              promise.future
            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }finally {
              destoryContext()
            }
          }
          

      }
      