package com.isuwang.soa.scala.hello.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class Hello(

         /**
        *
        **/
        
        content : String
        )
      